"""Models package for ARIA backend."""

from src.models.email_draft import (
    EmailDraftCreate,
    EmailDraftListResponse,
    EmailDraftPurpose,
    EmailDraftResponse,
    EmailDraftStatus,
    EmailDraftTone,
    EmailDraftUpdate,
    EmailRegenerateRequest,
    EmailSendResponse,
)
from src.models.meeting_brief import (
    AttendeeProfileResponse,
    BriefStatus,
    CompanyResearchResponse,
    GenerateBriefRequest,
    MeetingBriefContent,
    MeetingBriefResponse,
    UpcomingMeetingResponse,
)
from src.models.notification import (
    MarkReadRequest,
    NotificationCreate,
    NotificationListResponse,
    NotificationResponse,
    NotificationType,
    UnreadCountResponse,
)
from src.models.prediction import (
    AccuracySummaryResponse,
    CalibrationStatsResponse,
    ExtractedPrediction,
    PredictionCreate,
    PredictionResponse,
    PredictionStatus,
    PredictionType,
    PredictionUpdate,
    PredictionValidate,
)
from src.models.preferences import (
    DefaultTone,
    MeetingBriefLeadHours,
    PreferenceCreate,
    PreferenceResponse,
    PreferenceUpdate,
)
from src.models.feedback import (
    FeedbackRating,
    FeedbackResponse,
    FeedbackType,
    GeneralFeedbackRequest,
    ResponseFeedbackRequest,
)
from src.models.proactive_insight import (
    InsightType,
    ProactiveInsight,
    SurfacedInsightRecord,
)

__all__ = [
    "AccuracySummaryResponse",
    "AttendeeProfileResponse",
    "BriefStatus",
    "CalibrationStatsResponse",
    "CompanyResearchResponse",
    "DefaultTone",
    "EmailDraftCreate",
    "EmailDraftListResponse",
    "EmailDraftPurpose",
    "EmailDraftResponse",
    "EmailDraftStatus",
    "EmailDraftTone",
    "EmailDraftUpdate",
    "EmailRegenerateRequest",
    "EmailSendResponse",
    "FeedbackRating",
    "FeedbackResponse",
    "FeedbackType",
    "ExtractedPrediction",
    "GeneralFeedbackRequest",
    "GenerateBriefRequest",
    "MarkReadRequest",
    "MeetingBriefContent",
    "MeetingBriefLeadHours",
    "MeetingBriefResponse",
    "NotificationCreate",
    "NotificationListResponse",
    "NotificationResponse",
    "NotificationType",
    "PreferenceCreate",
    "PreferenceResponse",
    "PreferenceUpdate",
    "PredictionCreate",
    "PredictionResponse",
    "PredictionStatus",
    "PredictionType",
    "PredictionUpdate",
    "PredictionValidate",
    "ProactiveInsight",
    "InsightType",
    "ResponseFeedbackRequest",
    "SurfacedInsightRecord",
    "UnreadCountResponse",
    "UpcomingMeetingResponse",
]
