"""PDF generation for Execution Replay reports.

Renders a replay into a styled HTML template and converts it to PDF
using WeasyPrint.  WeasyPrint is lazily imported so environments that
do not have it installed can still use the rest of the codebase.
"""

import logging
from string import Template

from src.skills.replay_service import ExecutionReplayData

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# HTML template
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = Template(
    """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>ARIA Execution Replay - ${execution_id}</title>
<style>
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
                 Helvetica, Arial, sans-serif;
    font-size: 12px;
    color: #1a1a1a;
    margin: 40px;
    line-height: 1.5;
  }
  h1 { font-size: 20px; margin-bottom: 4px; }
  h2 { font-size: 15px; margin-top: 24px; border-bottom: 1px solid #ccc;
       padding-bottom: 4px; }
  .meta { color: #555; font-size: 11px; margin-bottom: 16px; }
  .badge {
    display: inline-block; padding: 2px 8px; border-radius: 4px;
    font-size: 11px; font-weight: 600; color: #fff;
  }
  .badge-success { background: #16a34a; }
  .badge-failure { background: #dc2626; }
  .badge-role { background: #6366f1; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; }
  th, td {
    text-align: left; padding: 6px 8px;
    border-bottom: 1px solid #e5e7eb;
  }
  th { background: #f9fafb; font-weight: 600; }
  .section { margin-bottom: 20px; }
  .redacted { color: #9ca3af; font-style: italic; }
  .footer {
    margin-top: 40px; font-size: 10px; color: #9ca3af;
    border-top: 1px solid #e5e7eb; padding-top: 8px;
  }
</style>
</head>
<body>
<h1>Execution Replay</h1>
<p class="meta">
  Skill: <strong>${skill_path}</strong> &middot;
  <span class="badge ${success_class}">${success_label}</span> &middot;
  ${timestamp}
  <span class="badge badge-role">${redaction_label}</span>
</p>

<div class="section">
<h2>Audit Entry</h2>
<table>
  <tr><th>Execution ID</th><td>${execution_id}</td></tr>
  <tr><th>Skill ID</th><td>${skill_id}</td></tr>
  <tr><th>Trust Level</th><td>${skill_trust_level}</td></tr>
  <tr><th>Trigger</th><td>${trigger_reason}</td></tr>
  <tr><th>Execution Time</th><td>${execution_time_ms} ms</td></tr>
  <tr><th>Data Classes Requested</th><td>${data_classes_requested}</td></tr>
  <tr><th>Data Classes Granted</th><td>${data_classes_granted}</td></tr>
  ${error_row}
</table>
</div>

${plan_section}
${steps_section}
${trust_section}

<div class="footer">
  Generated by ARIA &middot; Redaction tier: ${redaction_applied}
</div>
</body>
</html>"""
)

_PLAN_SECTION_TEMPLATE = Template(
    """\
<div class="section">
<h2>Execution Plan</h2>
<table>
  <tr><th>Plan ID</th><td>${plan_id}</td></tr>
  <tr><th>Task</th><td>${task_description}</td></tr>
  <tr><th>Status</th><td>${status}</td></tr>
  <tr><th>Risk Level</th><td>${risk_level}</td></tr>
  <tr><th>Estimated</th><td>${estimated_seconds}s</td></tr>
  <tr><th>Actual</th><td>${actual_seconds}s</td></tr>
  ${reasoning_row}
</table>
</div>"""
)

_STEP_ROW_TEMPLATE = Template(
    """\
  <tr>
    <td>${step_number}</td>
    <td>${skill_id}</td>
    <td>${input_summary}</td>
    <td>${output_summary}</td>
    <td>${status}</td>
    <td>${execution_time_ms} ms</td>
  </tr>"""
)

_TRUST_SECTION_TEMPLATE = Template(
    """\
<div class="section">
<h2>Trust Impact</h2>
<table>
  <tr><th></th><th>Before</th><th>After</th></tr>
  <tr>
    <td>Successful Executions</td>
    <td>${before_success}</td>
    <td>${after_success}</td>
  </tr>
  <tr>
    <td>Failed Executions</td>
    <td>${before_failure}</td>
    <td>${after_failure}</td>
  </tr>
  <tr>
    <td>Session Trust</td>
    <td colspan="2">${session_trust}</td>
  </tr>
  <tr>
    <td>Globally Approved</td>
    <td colspan="2">${globally_approved}</td>
  </tr>
</table>
</div>"""
)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_replay_pdf(replay: ExecutionReplayData) -> bytes:
    """Render an execution replay as a PDF document.

    The function lazily imports WeasyPrint.  If the library is not
    installed the caller receives a ``RuntimeError``.

    Args:
        replay: The replay data (already redacted).

    Returns:
        PDF file content as bytes.

    Raises:
        RuntimeError: If WeasyPrint is not available.
    """
    try:
        from weasyprint import HTML  # type: ignore[import-untyped]
    except ImportError as exc:
        logger.error("WeasyPrint is not installed; cannot generate PDF")
        raise RuntimeError(
            "PDF generation requires WeasyPrint. Install it with: pip install weasyprint"
        ) from exc

    html_str = _render_html(replay)
    pdf_bytes: bytes = HTML(string=html_str).write_pdf()  # type: ignore[no-untyped-call]
    return pdf_bytes


def render_replay_html(replay: ExecutionReplayData) -> str:
    """Render an execution replay as an HTML string (useful for previews).

    Args:
        replay: The replay data (already redacted).

    Returns:
        The rendered HTML string.
    """
    return _render_html(replay)


# ---------------------------------------------------------------------------
# Internal rendering
# ---------------------------------------------------------------------------


def _render_html(replay: ExecutionReplayData) -> str:
    """Build the full HTML document from the replay model.

    Args:
        replay: The replay data to render.

    Returns:
        The rendered HTML string.
    """
    success_class = "badge-success" if replay.success else "badge-failure"
    success_label = "Success" if replay.success else "Failed"
    redaction_label = f"View: {replay.redaction_applied}"

    error_row = ""
    if replay.error:
        error_row = f"  <tr><th>Error</th><td>{_esc(replay.error)}</td></tr>"

    plan_section = _render_plan_section(replay)
    steps_section = _render_steps_section(replay)
    trust_section = _render_trust_section(replay)

    return _HTML_TEMPLATE.safe_substitute(
        execution_id=_esc(replay.execution_id),
        skill_id=_esc(replay.skill_id),
        skill_path=_esc(replay.skill_path),
        skill_trust_level=_esc(replay.skill_trust_level),
        trigger_reason=_esc(replay.trigger_reason or "N/A"),
        execution_time_ms=replay.execution_time_ms or 0,
        data_classes_requested=_esc(", ".join(replay.data_classes_requested) or "None"),
        data_classes_granted=_esc(", ".join(replay.data_classes_granted) or "None"),
        success_class=success_class,
        success_label=success_label,
        redaction_label=redaction_label,
        timestamp=_esc(replay.timestamp or "N/A"),
        error_row=error_row,
        plan_section=plan_section,
        steps_section=steps_section,
        trust_section=trust_section,
        redaction_applied=_esc(replay.redaction_applied),
    )


def _render_plan_section(replay: ExecutionReplayData) -> str:
    """Render the execution plan HTML section.

    Args:
        replay: The replay data.

    Returns:
        HTML string for the plan section, or empty string if no plan.
    """
    plan = replay.execution_plan
    if plan is None:
        return '<div class="section"><h2>Execution Plan</h2><p class="redacted">No execution plan found.</p></div>'

    reasoning_row = ""
    if plan.reasoning:
        reasoning_row = f"  <tr><th>Reasoning</th><td>{_esc(plan.reasoning)}</td></tr>"

    return _PLAN_SECTION_TEMPLATE.safe_substitute(
        plan_id=_esc(plan.id),
        task_description=_esc(plan.task_description or "N/A"),
        status=_esc(plan.status or "N/A"),
        risk_level=_esc(plan.risk_level or "N/A"),
        estimated_seconds=plan.estimated_seconds or 0,
        actual_seconds=plan.actual_seconds or 0,
        reasoning_row=reasoning_row,
    )


def _render_steps_section(replay: ExecutionReplayData) -> str:
    """Render the working memory steps HTML section.

    Args:
        replay: The replay data.

    Returns:
        HTML string for the steps section.
    """
    steps = replay.working_memory_steps
    if not steps:
        return '<div class="section"><h2>Working Memory Steps</h2><p class="redacted">No steps recorded.</p></div>'

    rows = ""
    for step in steps:
        rows += _STEP_ROW_TEMPLATE.safe_substitute(
            step_number=step.step_number,
            skill_id=_esc(step.skill_id or "N/A"),
            input_summary=_esc(step.input_summary or "N/A"),
            output_summary=_esc(step.output_summary or "N/A"),
            status=_esc(step.status or "N/A"),
            execution_time_ms=step.execution_time_ms or 0,
        )

    return (
        '<div class="section">'
        "<h2>Working Memory Steps</h2>"
        "<table>"
        "  <tr><th>#</th><th>Skill</th><th>Input</th>"
        "<th>Output</th><th>Status</th><th>Time</th></tr>"
        f"{rows}"
        "</table>"
        "</div>"
    )


def _render_trust_section(replay: ExecutionReplayData) -> str:
    """Render the trust impact HTML section.

    Args:
        replay: The replay data.

    Returns:
        HTML string for the trust impact section.
    """
    impact = replay.trust_impact
    if impact is None:
        return '<div class="section"><h2>Trust Impact</h2><p class="redacted">No trust data available.</p></div>'

    return _TRUST_SECTION_TEMPLATE.safe_substitute(
        before_success=impact.successful_executions_before,
        after_success=impact.successful_executions_after,
        before_failure=impact.failed_executions_before,
        after_failure=impact.failed_executions_after,
        session_trust="Yes" if impact.session_trust_granted else "No",
        globally_approved="Yes" if impact.globally_approved else "No",
    )


def _esc(value: str) -> str:
    """Minimal HTML escaping for template values.

    Args:
        value: The raw string.

    Returns:
        The escaped string safe for HTML insertion.
    """
    return (
        value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
    )
