/**
 * UpcomingMeetings - Pre-meeting research visibility
 *
 * Shows upcoming calendar meetings with expandable research briefs
 * generated by ARIA's Scout agent. Each meeting card can be expanded
 * to view attendee profiles, talking points, suggested agenda, and
 * risks/opportunities.
 *
 * Follows ARIA Design System v1.0:
 * - LIGHT THEME (Actions page is a content page)
 * - CSS variables for all colors
 * - Lucide icons only, no emoji
 * - ARIA drives: briefs are auto-generated or user-triggered
 */

import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Calendar,
  ChevronDown,
  ChevronRight,
  Users,
  Loader2,
  FileText,
  AlertTriangle,
  Lightbulb,
} from 'lucide-react';
import { cn } from '@/utils/cn';
import {
  useUpcomingMeetings,
  useMeetingBrief,
  useGenerateMeetingBrief,
} from '@/hooks/useMeetingBrief';
import type {
  UpcomingMeeting,
  MeetingBriefContent as BriefContent,
  AttendeeProfile,
  MeetingBriefStatus,
} from '@/api/meetingBriefs';

// --- Status Badge ---

const STATUS_CONFIG: Record<
  MeetingBriefStatus,
  { label: string; color: string }
> = {
  completed: { label: 'Ready', color: 'var(--success)' },
  generating: { label: 'Generating...', color: 'var(--accent)' },
  pending: { label: 'Pending', color: 'var(--warning)' },
  failed: { label: 'Failed', color: 'var(--critical)' },
};

function StatusBadge({ status }: { status: MeetingBriefStatus | null }) {
  if (!status) return null;

  const config = STATUS_CONFIG[status];

  return (
    <span
      className="px-2 py-0.5 rounded-full text-xs font-medium whitespace-nowrap"
      style={{
        backgroundColor: `${config.color}20`,
        color: config.color,
      }}
    >
      {config.label}
    </span>
  );
}

// --- Meeting Time Formatter ---

function formatMeetingTime(dateString: string): { time: string; date: string } {
  const date = new Date(dateString);
  const now = new Date();
  const isToday = date.toDateString() === now.toDateString();

  const tomorrow = new Date(now);
  tomorrow.setDate(tomorrow.getDate() + 1);
  const isTomorrow = date.toDateString() === tomorrow.toDateString();

  const time = date.toLocaleTimeString([], {
    hour: 'numeric',
    minute: '2-digit',
  });

  let dateLabel: string;
  if (isToday) {
    dateLabel = 'Today';
  } else if (isTomorrow) {
    dateLabel = 'Tomorrow';
  } else {
    dateLabel = date.toLocaleDateString([], {
      weekday: 'short',
      month: 'short',
      day: 'numeric',
    });
  }

  return { time, date: dateLabel };
}

// --- Skeleton ---

function MeetingsSkeleton() {
  return (
    <div className="space-y-3 animate-pulse">
      {Array.from({ length: 3 }).map((_, i) => (
        <div
          key={i}
          className="border border-[var(--border)] rounded-lg p-4"
          style={{ backgroundColor: 'var(--bg-elevated)' }}
        >
          <div className="flex items-center gap-3">
            <div className="h-4 w-16 bg-[var(--border)] rounded" />
            <div className="h-4 w-48 bg-[var(--border)] rounded" />
            <div className="ml-auto h-5 w-20 bg-[var(--border)] rounded-full" />
          </div>
        </div>
      ))}
    </div>
  );
}

// --- Attendee Card ---

function AttendeeCard({ attendee }: { attendee: AttendeeProfile }) {
  return (
    <div
      className="border rounded-lg p-3"
      style={{
        borderColor: 'var(--border)',
        backgroundColor: 'var(--bg-primary)',
      }}
    >
      <div className="flex items-start justify-between gap-2 mb-2">
        <div className="min-w-0">
          <p
            className="font-medium text-sm truncate"
            style={{ color: 'var(--text-primary)' }}
          >
            {attendee.name || attendee.email}
          </p>
          {attendee.title && (
            <p
              className="text-xs truncate"
              style={{ color: 'var(--text-secondary)' }}
            >
              {attendee.title}
              {attendee.company ? ` at ${attendee.company}` : ''}
            </p>
          )}
        </div>
        {attendee.linkedin_url && (
          <a
            href={attendee.linkedin_url}
            target="_blank"
            rel="noopener noreferrer"
            className="text-xs flex-shrink-0 hover:underline"
            style={{ color: 'var(--accent)' }}
          >
            LinkedIn
          </a>
        )}
      </div>

      {attendee.background && (
        <p
          className="text-xs mb-2 leading-relaxed"
          style={{ color: 'var(--text-secondary)' }}
        >
          {attendee.background}
        </p>
      )}

      {attendee.talking_points.length > 0 && (
        <div className="mt-2">
          <p
            className="text-xs font-medium mb-1"
            style={{ color: 'var(--text-primary)' }}
          >
            Talking Points
          </p>
          <ul className="space-y-1">
            {attendee.talking_points.map((point, idx) => (
              <li
                key={idx}
                className="text-xs flex items-start gap-1.5"
                style={{ color: 'var(--text-secondary)' }}
              >
                <span
                  className="mt-1.5 w-1 h-1 rounded-full flex-shrink-0"
                  style={{ backgroundColor: 'var(--accent)' }}
                />
                {point}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}

// --- Brief Content Display ---

function BriefContentDisplay({ content }: { content: BriefContent }) {
  return (
    <div className="space-y-4 mt-4 pt-4 border-t border-[var(--border)]">
      {/* Summary */}
      <div>
        <div className="flex items-center gap-1.5 mb-2">
          <FileText className="w-3.5 h-3.5" style={{ color: 'var(--accent)' }} />
          <p
            className="text-xs font-medium uppercase tracking-wider"
            style={{ color: 'var(--text-secondary)' }}
          >
            Summary
          </p>
        </div>
        <p
          className="text-sm leading-relaxed"
          style={{ color: 'var(--text-primary)' }}
        >
          {content.summary}
        </p>
      </div>

      {/* Attendee Profiles */}
      {content.attendees.length > 0 && (
        <div>
          <div className="flex items-center gap-1.5 mb-2">
            <Users className="w-3.5 h-3.5" style={{ color: 'var(--accent)' }} />
            <p
              className="text-xs font-medium uppercase tracking-wider"
              style={{ color: 'var(--text-secondary)' }}
            >
              Attendees ({content.attendees.length})
            </p>
          </div>
          <div className="space-y-2">
            {content.attendees.map((attendee) => (
              <AttendeeCard key={attendee.email} attendee={attendee} />
            ))}
          </div>
        </div>
      )}

      {/* Company Research */}
      {content.company && (
        <div>
          <p
            className="text-xs font-medium uppercase tracking-wider mb-2"
            style={{ color: 'var(--text-secondary)' }}
          >
            Company: {content.company.name}
          </p>
          <div
            className="border rounded-lg p-3"
            style={{
              borderColor: 'var(--border)',
              backgroundColor: 'var(--bg-primary)',
            }}
          >
            {content.company.industry && (
              <p
                className="text-xs mb-1"
                style={{ color: 'var(--text-secondary)' }}
              >
                <span className="font-medium" style={{ color: 'var(--text-primary)' }}>
                  Industry:
                </span>{' '}
                {content.company.industry}
                {content.company.size ? ` | ${content.company.size}` : ''}
              </p>
            )}
            {content.company.our_history && (
              <p
                className="text-xs mt-1"
                style={{ color: 'var(--text-secondary)' }}
              >
                <span className="font-medium" style={{ color: 'var(--text-primary)' }}>
                  Our History:
                </span>{' '}
                {content.company.our_history}
              </p>
            )}
            {content.company.recent_news.length > 0 && (
              <div className="mt-2">
                <p
                  className="text-xs font-medium mb-1"
                  style={{ color: 'var(--text-primary)' }}
                >
                  Recent News
                </p>
                <ul className="space-y-1">
                  {content.company.recent_news.map((news, idx) => (
                    <li
                      key={idx}
                      className="text-xs flex items-start gap-1.5"
                      style={{ color: 'var(--text-secondary)' }}
                    >
                      <span
                        className="mt-1.5 w-1 h-1 rounded-full flex-shrink-0"
                        style={{ backgroundColor: 'var(--warning)' }}
                      />
                      {news}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Suggested Agenda */}
      {content.suggested_agenda.length > 0 && (
        <div>
          <p
            className="text-xs font-medium uppercase tracking-wider mb-2"
            style={{ color: 'var(--text-secondary)' }}
          >
            Suggested Agenda
          </p>
          <ol className="space-y-1">
            {content.suggested_agenda.map((item, idx) => (
              <li
                key={idx}
                className="text-sm flex items-start gap-2"
                style={{ color: 'var(--text-primary)' }}
              >
                <span
                  className="font-mono text-xs mt-0.5 flex-shrink-0"
                  style={{ color: 'var(--accent)' }}
                >
                  {idx + 1}.
                </span>
                {item}
              </li>
            ))}
          </ol>
        </div>
      )}

      {/* Risks & Opportunities */}
      {content.risks_opportunities.length > 0 && (
        <div>
          <div className="flex items-center gap-1.5 mb-2">
            <Lightbulb className="w-3.5 h-3.5" style={{ color: 'var(--warning)' }} />
            <p
              className="text-xs font-medium uppercase tracking-wider"
              style={{ color: 'var(--text-secondary)' }}
            >
              Risks & Opportunities
            </p>
          </div>
          <ul className="space-y-1">
            {content.risks_opportunities.map((item, idx) => (
              <li
                key={idx}
                className="text-sm flex items-start gap-1.5"
                style={{ color: 'var(--text-primary)' }}
              >
                <span
                  className="mt-1.5 w-1.5 h-1.5 rounded-full flex-shrink-0"
                  style={{ backgroundColor: 'var(--warning)' }}
                />
                {item}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}

// --- Meeting Card ---

function MeetingCard({ meeting }: { meeting: UpcomingMeeting }) {
  const [expanded, setExpanded] = useState(false);
  const { time, date } = formatMeetingTime(meeting.meeting_time);

  // Only fetch brief data when card is expanded
  const {
    data: briefData,
    isLoading: briefLoading,
    error: briefError,
  } = useMeetingBrief(expanded ? meeting.calendar_event_id : '');

  const generateBrief = useGenerateMeetingBrief();

  const handleGenerateBrief = () => {
    generateBrief.mutate({
      calendarEventId: meeting.calendar_event_id,
      request: {
        meeting_title: meeting.meeting_title,
        meeting_time: meeting.meeting_time,
        attendee_emails: meeting.attendees,
      },
    });
  };

  const hasBriefContent =
    briefData?.status === 'completed' &&
    briefData.brief_content &&
    'summary' in briefData.brief_content;

  const isGenerating =
    meeting.brief_status === 'generating' ||
    briefData?.status === 'generating' ||
    generateBrief.isPending;

  const hasFailed =
    !isGenerating &&
    (meeting.brief_status === 'failed' || briefData?.status === 'failed');

  const displayStatus: MeetingBriefStatus | null =
    briefData?.status ?? meeting.brief_status;

  return (
    <div
      className={cn(
        'border rounded-lg transition-all duration-200',
        expanded && 'shadow-sm'
      )}
      style={{
        borderColor: expanded ? 'var(--accent)' : 'var(--border)',
        backgroundColor: 'var(--bg-elevated)',
      }}
    >
      {/* Collapsed header - always visible */}
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full text-left p-4 flex items-center gap-3"
      >
        {expanded ? (
          <ChevronDown
            className="w-4 h-4 flex-shrink-0"
            style={{ color: 'var(--text-secondary)' }}
          />
        ) : (
          <ChevronRight
            className="w-4 h-4 flex-shrink-0"
            style={{ color: 'var(--text-secondary)' }}
          />
        )}

        {/* Time */}
        <div className="flex-shrink-0 w-24">
          <p
            className="font-mono text-sm"
            style={{ color: 'var(--accent)' }}
          >
            {time}
          </p>
          <p
            className="font-mono text-xs"
            style={{ color: 'var(--text-secondary)' }}
          >
            {date}
          </p>
        </div>

        {/* Title */}
        <div className="min-w-0 flex-1">
          <p
            className="text-sm font-medium truncate"
            style={{ color: 'var(--text-primary)' }}
          >
            {meeting.meeting_title || 'Untitled Meeting'}
          </p>
          <div className="flex items-center gap-1 mt-0.5">
            <Users
              className="w-3 h-3"
              style={{ color: 'var(--text-secondary)' }}
            />
            <span
              className="text-xs"
              style={{ color: 'var(--text-secondary)' }}
            >
              {meeting.attendees.length} attendee
              {meeting.attendees.length !== 1 ? 's' : ''}
            </span>
          </div>
        </div>

        {/* Status badge */}
        <StatusBadge status={displayStatus} />
      </button>

      {/* Expanded content */}
      {expanded && (
        <div className="px-4 pb-4 pl-11">
          {/* Loading brief */}
          {briefLoading && !briefData && (
            <div className="flex items-center gap-2 py-4">
              <Loader2
                className="w-4 h-4 animate-spin"
                style={{ color: 'var(--accent)' }}
              />
              <span
                className="text-sm"
                style={{ color: 'var(--text-secondary)' }}
              >
                Loading brief...
              </span>
            </div>
          )}

          {/* Brief is generating */}
          {isGenerating && !hasBriefContent && (
            <div className="flex items-center gap-2 py-4">
              <Loader2
                className="w-4 h-4 animate-spin"
                style={{ color: 'var(--accent)' }}
              />
              <span
                className="text-sm"
                style={{ color: 'var(--text-secondary)' }}
              >
                Generating research brief...
              </span>
            </div>
          )}

          {/* Brief failed */}
          {hasFailed && (
            <div className="flex items-center gap-2 py-4">
              <AlertTriangle
                className="w-4 h-4 flex-shrink-0"
                style={{ color: 'var(--critical)' }}
              />
              <span
                className="text-sm"
                style={{ color: 'var(--critical)' }}
              >
                {briefData?.error_message || 'Brief generation failed.'}
              </span>
              <button
                onClick={handleGenerateBrief}
                className="ml-2 text-xs font-medium px-2 py-1 rounded hover:opacity-80 transition-opacity"
                style={{
                  backgroundColor: 'var(--accent)',
                  color: 'white',
                }}
              >
                Retry
              </button>
            </div>
          )}

          {/* Brief not generated yet */}
          {!briefLoading &&
            !isGenerating &&
            !hasFailed &&
            !hasBriefContent &&
            (!briefError || meeting.brief_status === null) && (
              <div className="flex items-center gap-3 py-4">
                <FileText
                  className="w-4 h-4"
                  style={{ color: 'var(--text-secondary)' }}
                />
                <span
                  className="text-sm"
                  style={{ color: 'var(--text-secondary)' }}
                >
                  No research brief yet.
                </span>
                <button
                  onClick={handleGenerateBrief}
                  disabled={generateBrief.isPending}
                  className={cn(
                    'text-sm font-medium px-3 py-1.5 rounded-lg transition-opacity',
                    'hover:opacity-90',
                    generateBrief.isPending && 'opacity-50 cursor-not-allowed'
                  )}
                  style={{
                    backgroundColor: 'var(--accent)',
                    color: 'white',
                  }}
                >
                  Generate Brief
                </button>
              </div>
            )}

          {/* Brief content */}
          {hasBriefContent && (
            <BriefContentDisplay
              content={briefData.brief_content as BriefContent}
            />
          )}
        </div>
      )}
    </div>
  );
}

// --- Main Component ---

export function UpcomingMeetings() {
  const navigate = useNavigate();
  const { data: meetings, isLoading, error } = useUpcomingMeetings(5);

  const hasMeetings = meetings && meetings.length > 0;

  return (
    <section className="mb-8" data-aria-id="upcoming-meetings">
      {/* Section header */}
      <div className="flex items-center gap-2 mb-1">
        <Calendar
          className="w-4 h-4"
          style={{ color: 'var(--text-primary)' }}
        />
        <h2
          className="font-sans text-sm font-medium"
          style={{ color: 'var(--text-primary)' }}
        >
          Upcoming Meetings
        </h2>
      </div>
      <p
        className="text-xs mb-4 ml-6"
        style={{ color: 'var(--text-secondary)' }}
      >
        Pre-meeting research from ARIA&apos;s Scout agent
      </p>

      {/* Loading state */}
      {isLoading && <MeetingsSkeleton />}

      {/* Error state */}
      {error && !isLoading && (
        <div
          className="text-center py-6"
          style={{ color: 'var(--text-secondary)' }}
        >
          Error loading meetings.
        </div>
      )}

      {/* Empty state */}
      {!isLoading && !error && !hasMeetings && (
        <div
          className="border border-[var(--border)] rounded-lg py-8 px-4 text-center"
          style={{ backgroundColor: 'var(--bg-elevated)' }}
        >
          <Calendar
            className="w-6 h-6 mx-auto mb-2"
            style={{ color: 'var(--text-secondary)', opacity: 0.5 }}
          />
          <p
            className="text-sm mb-1"
            style={{ color: 'var(--text-secondary)' }}
          >
            No upcoming meetings.
          </p>
          <button
            onClick={() => navigate('/settings')}
            className="text-xs hover:underline"
            style={{ color: 'var(--accent)' }}
          >
            Connect your calendar in Settings
          </button>
        </div>
      )}

      {/* Meeting list */}
      {!isLoading && !error && hasMeetings && (
        <div className="space-y-3">
          {meetings.map((meeting) => (
            <MeetingCard
              key={meeting.calendar_event_id}
              meeting={meeting}
            />
          ))}
        </div>
      )}
    </section>
  );
}
