"""
ARIA Reasoning Engine.

Generates expert-level strategic reasoning narratives that explain WHY
ARIA took an action, WHAT intelligence informed her decision, and WHAT
the user should do next.

This is the trust layer. Every work product ARIA creates gets a reasoning
narrative that shows her work at a level that would impress a VP of Sales.

The reasoning is generated by a dedicated LLM call at work-product creation
time and stored alongside the work product. It is NOT assembled from
database fields at display time.
"""
import logging
from typing import Optional

logger = logging.getLogger(__name__)


class ReasoningEngine:
    """Generates strategic reasoning narratives for ARIA's work products."""

    def __init__(self, supabase_client):
        self._db = supabase_client

    async def generate_email_reasoning(
        self,
        user_company: str,
        competitor_name: str,
        signal_context: str,
        competitive_positioning: dict,
        email_body: str,
        user_goals: list[dict] | None = None,
        digital_twin: dict | None = None,
    ) -> str:
        """
        Generate reasoning narrative for a competitive displacement email.

        This explains WHY ARIA wrote this specific email, WHAT intelligence
        informed each choice, and WHAT the user should do next.
        """
        differentiation = competitive_positioning.get("differentiation", [])
        weaknesses = competitive_positioning.get("weaknesses", [])
        pricing = competitive_positioning.get("pricing", {})

        goals_context = ""
        if user_goals:
            goals_context = "USER'S ACTIVE GOALS:\n" + "\n".join(
                f"- {g.get('title', '')}" for g in user_goals[:3]
            )

        twin_context = ""
        if digital_twin:
            twin_context = (
                f"USER'S WRITING STYLE: {digital_twin.get('writing_style', 'concise and direct')} "
                f"| Formality: {digital_twin.get('formality_level', 'business')}"
            )

        prompt = f"""You are ARIA, an autonomous AI colleague for life sciences commercial teams.
You just drafted a competitive displacement email for a sales professional at {user_company}.

Explain your reasoning to the user. Write as if you're a brilliant sales strategist
who just did 2 hours of competitive analysis in 10 seconds. Be specific, be strategic,
connect the dots between the signal, the competitive intelligence, and the email choices.

THE SIGNAL THAT TRIGGERED THIS:
{signal_context}

COMPETITIVE INTELLIGENCE YOU USED:
Competitor: {competitor_name}
Your advantages: {'; '.join(str(d) for d in differentiation[:3]) if differentiation else 'N/A'}
Their vulnerabilities: {'; '.join(str(w) for w in weaknesses[:3]) if weaknesses else 'N/A'}
Their pricing: {pricing.get('range', 'N/A') if isinstance(pricing, dict) else 'N/A'} — {pricing.get('notes', '') if isinstance(pricing, dict) else ''}
Their strategy: {pricing.get('strategy', '') if isinstance(pricing, dict) else ''}

{goals_context}

{twin_context}

THE EMAIL YOU WROTE:
{email_body[:500]}

Write a 150-200 word reasoning brief with these sections (use these exact headers):

THE SIGNAL
One sentence on what happened and why it matters commercially. Be specific.

WHY THIS IS A DISPLACEMENT WINDOW
2-3 sentences connecting the signal to the specific competitive vulnerability.
Reference the competitor's specific weaknesses and how the signal amplifies them.
Reference the user's specific advantages and why NOW is the moment to use them.
If relevant, connect to the user's active goals.

HOW I POSITIONED THE EMAIL
2-3 sentences explaining specific choices in the email. Why you led with X,
why you avoided Y, why the CTA is structured the way it is. Reference which
battle card data informed each choice.

WHAT TO DO NEXT
3-4 bullet points of specific, actionable next steps. Not generic advice —
specific to THIS signal, THIS competitor, THIS email.

Rules:
- Be specific. Reference actual product names, pricing figures, strategic details.
- Be strategic. Connect dots the user might not see.
- Be concise. Every sentence should add value.
- Never use generic filler like "this creates an opportunity" without saying WHAT opportunity.
- Write in first person as ARIA: "I led with..." not "The email leads with..."
"""

        try:
            from src.core.llm import LLMClient
            from src.core.task_types import TaskType

            llm = LLMClient()
            response = await llm.generate_response(
                task=TaskType.ANALYST_RESEARCH,
                messages=[{"role": "user", "content": prompt}],
                system_prompt=(
                    "You are ARIA, a super-intelligent AI colleague. Write strategic reasoning "
                    "briefs that would impress a VP of Sales at a life sciences company. "
                    "Be specific, be brilliant, connect dots humans would miss."
                ),
            )

            reasoning = str(response).strip()

            if len(reasoning) < 50:
                return self._fallback_email_reasoning(
                    competitor_name, signal_context, competitive_positioning
                )

            return reasoning

        except Exception as e:
            logger.error("[ReasoningEngine] Email reasoning generation failed: %s", e)
            return self._fallback_email_reasoning(
                competitor_name, signal_context, competitive_positioning
            )

    async def generate_proposal_reasoning(
        self,
        user_company: str,
        competitor_name: str,
        entity_type: str,
        signal_context: str,
        insight_content: str,
        competitive_positioning: dict,
        user_goals: list[dict] | None = None,
    ) -> str:
        """
        Generate reasoning narrative for a proactive proposal / action card.

        This explains WHY ARIA is proposing this action and what the user
        gains by approving it.
        """
        differentiation = competitive_positioning.get("differentiation", [])
        weaknesses = competitive_positioning.get("weaknesses", [])
        pricing = competitive_positioning.get("pricing", {})

        goals_context = ""
        if user_goals:
            goals_context = "USER'S ACTIVE GOALS:\n" + "\n".join(
                f"- {g.get('title', '')}" for g in user_goals[:3]
            )

        prompt = f"""You are ARIA, an autonomous AI colleague for life sciences commercial teams.
You detected a competitive intelligence signal and are proposing an action to a sales
professional at {user_company}.

Explain why you're proposing this action. Be specific, strategic, and connect the dots.

SIGNAL: {signal_context[:300]}
INSIGHT: {insight_content[:300]}
COMPETITOR: {competitor_name} (entity type: {entity_type})
YOUR ADVANTAGES: {'; '.join(str(d) for d in differentiation[:3]) if differentiation else 'N/A'}
THEIR VULNERABILITIES: {'; '.join(str(w) for w in weaknesses[:3]) if weaknesses else 'N/A'}
THEIR PRICING: {pricing.get('range', 'N/A') if isinstance(pricing, dict) else 'N/A'}
{goals_context}

Write a 100-150 word reasoning brief explaining:
1. What you detected and why it matters (1-2 sentences)
2. What specific competitive vulnerability this creates (1-2 sentences)
3. What you're proposing and why it will work (2-3 sentences)
4. What happens if the user doesn't act (1 sentence)

Rules:
- Be specific. Use actual product names, pricing, market details.
- Write in first person as ARIA.
- Every sentence must add strategic value. No filler.
"""

        try:
            from src.core.llm import LLMClient
            from src.core.task_types import TaskType

            llm = LLMClient()
            response = await llm.generate_response(
                task=TaskType.ANALYST_RESEARCH,
                messages=[{"role": "user", "content": prompt}],
                system_prompt=(
                    "You are ARIA. Write strategic reasoning that would impress "
                    "a VP of Sales. Be specific and brilliant."
                ),
            )

            reasoning = str(response).strip()
            if len(reasoning) < 50:
                return self._fallback_proposal_reasoning(competitor_name, signal_context)
            return reasoning

        except Exception as e:
            logger.error("[ReasoningEngine] Proposal reasoning failed: %s", e)
            return self._fallback_proposal_reasoning(competitor_name, signal_context)

    async def generate_conference_reasoning(
        self,
        user_company: str,
        conference_name: str,
        conference_date: str,
        competitor_count: int,
        prospect_count: int,
        topic_relevance: float,
        reasons: list[dict],
        battle_briefs: list[dict] | None = None,
    ) -> str:
        """Generate reasoning for conference recommendation."""
        battle_info = ""
        if battle_briefs:
            battle_info = (
                f"- Battle card competitors present: "
                f"{', '.join(b.get('competitor', '') for b in battle_briefs[:3])}"
            )

        prompt = f"""You are ARIA. Explain to a sales professional at {user_company} why
they should attend {conference_name} ({conference_date}).

FACTS:
- {competitor_count} competitors exhibiting
- {prospect_count} prospects presenting
- Topic relevance to your focus: {topic_relevance:.0%}
- Key reasons: {'; '.join(r.get('reason', '') for r in reasons[:3])}
{battle_info}

Write 3-4 sentences explaining why this conference matters strategically.
Be specific about what competitive intelligence they can gather and which
prospects they should target. Write in first person as ARIA."""

        try:
            from src.core.llm import LLMClient
            from src.core.task_types import TaskType

            llm = LLMClient()
            response = await llm.generate_response(
                task=TaskType.CAUSAL_CLASSIFY,
                messages=[{"role": "user", "content": prompt}],
                system_prompt="You are ARIA. Write concise strategic reasoning.",
            )
            reasoning = str(response).strip()
            return reasoning
        except Exception:
            return (
                f"{conference_name} has {competitor_count} competitors and "
                f"{prospect_count} prospects relevant to your focus areas."
            )

    def _fallback_email_reasoning(
        self, competitor: str, signal: str, positioning: dict
    ) -> str:
        diff = positioning.get("differentiation", [])
        diff_text = diff[0] if diff else "your specialized solutions"
        return f"""THE SIGNAL
{signal[:200]}

WHY THIS IS A DISPLACEMENT WINDOW
{competitor}'s supply chain disruption creates an immediate opening. Their customers need alternatives now, and your {diff_text} is the most direct competitive answer.

HOW I POSITIONED THE EMAIL
I led with supply continuity value rather than naming {competitor}'s issue directly. Life sciences is a small industry. I kept the CTA low-friction (15-minute call) because this is likely cold outreach.

WHAT TO DO NEXT
- Replace [Contact Name] with your best contact at an account using {competitor}
- Send within 5 business days while the signal is fresh
- If no response in 7 days, I'll draft a follow-up"""

    def _fallback_proposal_reasoning(self, competitor: str, signal: str) -> str:
        return (
            f"I detected a competitive signal involving {competitor}: {signal[:150]}. "
            f"This creates a displacement window. I'm proposing outreach using your "
            f"battle card positioning to capture accounts that may be reconsidering "
            f"their supplier relationship."
        )
